name: Publish from master

on:
  push: 
    branches: [master, feature_1.0]
env:
  webapp_name: openhackz6y6y8p2poi
defaults:
  run:
    shell: bash
    working-directory: apis/poi/web/ 
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: openhackz6y6y8p2acr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t openhackz6y6y8p2acr.azurecr.io/app-poi:${{ github.sha }}
        docker push openhackz6y6y8p2acr.azurecr.io/app-poi:${{ github.sha }}
    - name: Azure CLI Start Staging Slot
      uses: Azure/cli@1.0.4
      with:
        inlineScript: az webapp start --name openhackz6y6y8p2poi --resource-group openhackz6y6y8p2rg --slot staging
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.webapp_name }}
        slot-name: staging 
        images: openhackz6y6y8p2acr.azurecr.io/app-poi:${{ github.sha }}         
    - uses: actions/github-script@0.9.0
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log:https://github.com/${{ github.repository}}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            body: body
            });
