name: Publish from master
env:
  CONTAINER_IMAGE: poi-image
on:
  push: 
    branches: [master, feature_1.0]
defaults:
  run:
    shell: bash
    working-directory: apis/poi/web/ 
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: openhackz6y6y8p2acr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t openhackz6y6y8p2acr.azurecr.io/poiimage:${{ github.sha }}
        docker push openhackz6y6y8p2acr.azurecr.io/poiimage:${{ github.sha }}
