name: .NET Core

on:
  push:
    branches: [ master, feature_1.0 ]
    paths: ['apis/poi/**']
  pull_request:
    branches: [ master ]
    paths: ['apis/poi/**']
defaults:
  run:
    shell: bash
    working-directory: apis/poi 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.*
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: |
        cd ../user-java
        dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: create-issue
    - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'
    - run: 'echo Created ${{ steps.create-issue.outputs.url }}'
